### ISSUE TITLE
Long transcriptions segmentation

### ISSUE THREAD

**Issue by yshalsager** [charslab/TranscriberBot#12]
I'd like to report a possible bug when a file is pretty long and text length is longer than the maximum allowed number of a single message. The bot sends only one message in this case and skips the rest.

This can be easily reproduced by sending any long file (20 minutes for example).

**Comment by carloalbertobarbano** [comment]
Hello, thanks for the feedback. This functionality is actually implemented, there shouldn't be any problem unless telegram significantly reduced the max message length..

**Comment by yshalsager** [comment]
Update: it's working fine now so I think something went wrong temporarily before.
