### ISSUE TITLE
Image transcription is not working

### ISSUE THREAD

**Issue by cipherbreaker** [charslab/TranscriberBot#26]
<p align="center">
  <img src="https://user-images.githubusercontent.com/80171256/110217368-8de47880-7eab-11eb-9891-b967ca6de3c5.png">
  <br/>
  <em><b>Figure 1.</b> Result from bot after sending an image with <b>/enable_photos</b> enabled.</em>
</p>

I have been trying to transcribe images whilst and within groups, for ease of access to blind members (they can use an app to read screen, but many of them can't read telegram images). The bot gets stuck at "Recognizing" for several minutes (in fact, days so far).

I thought that was some misconfiguration so, I have tried to upload a random image directly to bot and see if works. Sadly, it doesn't work too. Not sure if its a problem of certain images or it doesn't work anymore. Uploaded a sample image if you want to test or need some input on "failed" cases.

<p align="center">
  <img width=616 src="https://user-images.githubusercontent.com/80171256/110217369-8e7d0f00-7eab-11eb-84d5-2107067f90c0.png">
  <br/>
  <em><b>Figure 2.</b> Sample image provided for recognition.</em>
</p>

Don't get me wrong. Your bot is great and really helps transcribing audio. Great work!

Thanks in advance and hope to see this working again.

**Comment by stefanodelbosco** [comment]
Hi
I had found a problem with the OCR function two days ago.
I moved to the production the changes now, after some tests.

I add the link of the PR https://github.com/charslab/TranscriberBot/pull/25 with the changes.

I tried to recognize the image 'figure2' and the result is:

>Estimated Energy Adjustable Values
>Average hours of use per day Average CPU Utilization (0-100%) + Power cost, $ per kWh?
>24 50 0.8877
>
>1 Average user usage Is typically low and can vary from task to task. An estimate load 259% is nominal.
>2 Typical power costs vary around the world. Check your last power bill for details. Values of $0.15 to $0.45 per kWh are typical
>
>Intel Core Intel Core AMD Intel Core AMD
>i7-1065G7 @ FX-8320 '-8550U @ FX-8320E
>1.30GHz Eight-Core 1.80GHz Eight-Core
>Max TDP 15w 15W 125W sw 95w
>Power consumption per
>0.2 02 15 02 al
>day (kWh)
>Running cost per day $0.160 $0.160 $1.332 $0.160 $1.012
>Power consumption per
>65.7 657 547.5 657 416.1
>year (kWh)
>Running cost per year $58.32 $58.32 $486.02 $58.32 $369.37
>
>Shown CPU power usage Is based on linear interpolation of Max TDP (Le. max load). Actual CPU power profile may vary.
