### ISSUE TITLE
[Usability] Remove "text"/"recognized text" before result in private chat

### ISSUE THREAD

**Issue by turicas** [charslab/TranscriberBot#27]
The most use case for me is to record a voice clip, wait for transcription, copy the whole answer and then paste it in another place (I usually do this using a cellphone). I imagine this is the most use case in general for private chats.
Since I don't want to paste the "Text: " part of the message and it's hard to copy only a portion of the text in cellphones, I suggest removing these prefixes (strings `transcription_text` and `ocr_result`) in private chats. It's already clear that the answer is the transcribed text for that audio since it's an reply to the sent audio clip and well, the bot name is TranscriberBot! :)
What do you think?

**Comment by carloalbertobarbano** [comment]
Sorry for the late reply, I've been caught up with other work.. Yes I think this can be removed in private chats
