### ISSUE TITLE
Merge `development` into `master`?

### ISSUE THREAD

**Issue by turicas** [charslab/TranscriberBot#34]
I found that the `development` branch is behind `master` for some commits but also it has a new merge (PR #24) which hasn't been merged into `master` yet.
Are you going to merge it on `master` and deploy this new version (supports video files)?

![branches](https://user-images.githubusercontent.com/186126/118974194-ed99de00-b948-11eb-9ee6-0e1b43ee415a.png)

**Comment by stefanodelbosco** [comment]
At the moment the development branch is the current running version (in a docker container, with this [package](https://github.com/orgs/charslab/packages/container/package/transcriberbot))
But I made a mistake 2 month ago... I forgot to change and upload the new configs file (config/app.json), so the bot didn't recognized the video files...
Now there is the correct config file, so it will be able to recognize the video files and now the #24 will works

About the merge development into master, there are some things to do (for example GH Action, docker run instruction, etc) and at the moment I don't have time to do D:

**Comment by turicas** [comment]
@stefanodelbosco thanks a lot! :)
I didn't understand what should be done for the merge, if I can help please describe the needed actions. :)

**Comment by stefanodelbosco** [comment]
@turicas, I finally merge the development into master.
At the moment the running version is the master ('latest' of docker image)
