### ISSUE TITLE
the app is not working

### ISSUE THREAD

**Issue by 19092013** [charslab/TranscriberBot#35]
the app is not working

**Comment by turicas** [comment]
It can answer commands but won't transcribe any audio:
![Screenshot_20210601-134736](https://user-images.githubusercontent.com/186126/120361353-1d999780-c2e0-11eb-92cc-35025c4e2c3d.png)

**Comment by stefanodelbosco** [comment]
Docker container restarted, now its works.

**Comment by turicas** [comment]
Thanks, @stefanodelbosco!
