### ISSUE TITLE
The bot is not working again

### ISSUE THREAD

**Issue by mongolgen** [charslab/TranscriberBot#37]
Sorry to bother you sir
But the bot stopped working
Im so so sorry but I'm depending on it to sutdy for the finals 
![Screenshot_20210602-090004](https://user-images.githubusercontent.com/85187210/120431456-3017dd80-c381-11eb-9a63-42db968c711b.png)

**Comment by stefanodelbosco** [comment]
We are working to resolve the problem.
We apologize for the inconvenience
Transcriber bot will be back soon

**Comment by stefanodelbosco** [comment]
We had solve some problem and now it is online again
Thanks for your patience 😄
