### ISSUE TITLE
The bot is not working

### ISSUE THREAD

**Issue by Andrea65485** [charslab/TranscriberBot#7]
I tried to use it in English and Italian, but it can't transcribe anything anymore. It just continue to fail again and again

**Comment by Mohammed2wa** [comment]
حاولت استخدامه باللغتين الإنجليزية والعربية ، ولكن لم يعد بإمكانه نسخ أي شيء.
ويظهر لى هذه الرسالة
Could not transcribe audio
تحقيق

**Comment by carloalbertobarbano** [comment]
@Mohammed2wa can you keep it in english please?

**Comment by aersoares81** [comment]
It doesn’t work me either. It doesn’t respond to “/start”, I’ve tried multiple times over 3 days now.

**Comment by carloalbertobarbano** [comment]
I can confirm. There's is something wrong connecting to telegram server, it might be an issue with telegram APIs, or more probably we need to update to the latest version of python-telegram-bot. From the info I've been able to gather the situation is:
1. telegram APIs have been updated
2. python-telegram-bot has been updated
3. WIT APIs have been updated

So:
1. Would be solved by solving 2.
2. The source does not work with the latest version of python-telegram-bot 
3. I need to figure out what has changed or if this is related to 2. as well

I don't currently have much time though, so if anyone wants to help, you're welcome!

**Comment by Davte** [comment]
> I can confirm. There's is something wrong connecting to telegram server, it might be an issue with telegram APIs, or more probably we need to update to the latest version of python-telegram-bot. From the info I've been able to gather the situation is:
> 
>     1. telegram APIs have been updated
> 
>     2. python-telegram-bot has been updated
> 
>     3. WIT APIs have been updated
> 
> 
> So:
> 
>     1. Would be solved by solving 2.
> 
>     2. The source does not work with the latest version of python-telegram-bot
> 
>     3. I need to figure out what has changed or if this is related to 2. as well
> 
> 
> I don't currently have much time though, so if anyone wants to help, you're welcome!

I opened a pull request, with my patch a local copy of the bot answers to /start command and transcribes voice messages. I am not sure if it is a complete fix but it might.

1. I could not see if and how it was relevant
2. python-telegram-bot migration to v12
2.1 `use_context` parameter passed to Updater constructor (redundant in v13, but necessary in v12)
2.2 `__pre__hook` parameters changed (`bot, update` > `update, context`, `bot = context.bot`)
2.3 UTC specified for datetime in message age calculation
3. wit.ai API response json key renamed (`_text` > `text`)

**Comment by carloalbertobarbano** [comment]
Thanks @Davte your contributions have been merged into master and at the moment the bot is working with python-telegram-bot==12.3.0

**Comment by kumo-chan9** [comment]
> Thanks @Davte your contributions have been merged into master and at the moment the bot is working with python-telegram-bot==12.3.0

It's not working with me! ""(

**Comment by carloalbertobarbano** [comment]
> > Thanks @Davte your contributions have been merged into master and at the moment the bot is working with python-telegram-bot==12.3.0
> 
> It's not working with me! ""(

What do you mean? Can you provide details? The bot is currently live and working fine with version 12.3.0 on my end..
